# Generated by Django 5.1.1 on 2025-09-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_title_description_alter_title_year_review_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 10)), name='valid_score_range'),
        ),
    ]
